### ISSUE TITLE
Quick Remove Rule button

### ISSUE THREAD

**Issue by ponnchamy** [QuadSpinner/Highlighter#3]
1. We need a "Remove" button in the "Modify Hilight Rule" window, there we can remove easily.
2. Rules added with right click menu should be saved to "Solution Rules" not to "Global Rules"
3. When we add new rule, the shape option should be defaulted to the last chosen one

**Comment by daxpandhi** [comment]
Thanks for the feedback. Solution Rules are still in development, but yes once they're active it will be the default.

I'll try to implement all 3 in the next release in a week or so.

**Comment by daxpandhi** [comment]
All 3 suggestions have been implemented (albeit a little late), and will be released shortly once tested.
