### ISSUE TITLE
Ability to select substrings of words

### ISSUE THREAD

**Issue by bartosz-jarmuz** [QuadSpinner/Highlighter#4]
Hello,
This is an enhancement idea  - at the moment the highlighter only highlights full words.
Would it be possible to allow highlighting parts of the words too?

For example, create a rule for **Foo** should highlight:
1. IAbstract**Foo**Factory
2. **Foo**Processor
3. _listOfInactive**Foo** = new();

etc.
Ideally, separate rules for **Foo** and *Bar* should result in two highlights in one word, e.g.
var percentageOf**Foo**In*Bar*Collection = new();

This is useful in large codebases where you add 'a similar concept' as something that exists already (e.g. Foo) and there are many places where this Foo is used, so they should all stand out nicely.

Kind regards,

**Comment by daxpandhi** [comment]
Thanks for the feedback! This has been implemented and will be released in the next build shortly. :)
