### ISSUE TITLE
[BUG] VS2022 - Create/Edit Highlight rule doesn't work

### ISSUE THREAD

**Issue by Ares9323** [QuadSpinner/Highlighter#8]
I tried to use both the shortcut (CTRL + Num +) and the right click option, but nothing appears both in Global and Solution Rules.

**Comment by daxpandhi** [comment]
I'll investigate further. I'm using it VS 2022 and VS 2022 Preview both and it seems to work.

Is the Output showing any errors?

**Comment by Ares9323** [comment]
Sorry, I didn't notice it yesterday, here's the error:
`
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable'1 source, Func'2 predicate)
   at Highlighter.Commands.CreateHighlight.<ExecuteAsync>d__0.MoveNext() in Z:\Git\OSS\Highlighter\src\Commands\CreateHighlight.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand'1.<>c__DisplayClass10_0.<<Execute>b__0>d.MoveNext()
`
   
   Am I doing something wrong? I tried to select the entire word or just placing the cursor over it (the second one doesn't log at all)

**Comment by daxpandhi** [comment]
Thanks for the error, that helps a bit! What language file are you trying to highlight?

**Comment by Ares9323** [comment]
I'm working in C++ (Unreal C++ uses a lot of Macro and specific syntax), the extension doens't work in both .cpp and .h files.

I tried creating a simple cmake project with a "hello world" and the command doesn't work there too (same error in the console)

**Comment by daxpandhi** [comment]
I haven't tested it on C++ too much, so I probably missed something. I'll check and get back to you.

**Comment by daxpandhi** [comment]
It seems something may be missing in your options. Can you try going to Options dialog > Highlighter, and making a new tag manually? Then you should be able to make new highlights normally.

Or you can uninstall the extension and reinstall it. It seems like the actual settings (the array of existing highlights) is not available. I can't seem to reproduce the error on my end.

**Comment by Ares9323** [comment]
Actually, I am already using the extension and it works, I added tags manually, the problem is that I have to do it from the settings panel and the shortcuts aren't working.
Everytime I save the highlighter settings visual studio crashes (but they are saved and working at the next boot)

**Comment by daxpandhi** [comment]
I can't seem to reproduce it on any of my computers, or in a clean VM. It might be a local issue, but I'll keep investigating when I can and try to create some error handlers for this situation.

Not sure if this helps, but it will write solution-level settings to `<solution root>\.vs\Highlights.xml` - maybe it is a permissions issue?

**Comment by Ares9323** [comment]
> but it will write solution-level settings to `<solution root>\.vs\Highlights.xml` - maybe it is a permissions issue?

I have no file called like that in my .vs folder, I tried creating one but nothing changes. It shouldn't be a permission issue because the folder has no particular rules. 

Also, I can't add solution rules from the options window, only global:
![image](https://user-images.githubusercontent.com/46932745/196800099-69752c48-929a-4d57-a7bc-d428338b7a17.png)

**Comment by Ares9323** [comment]
I added "HighlightTag[] Array" in the "Solution rules" manually and now everything seems to work: the shortcuts are ok and the options window no longer crashes on save. Thank you for pointing me at the "solution-level settings".

Btw I still have no .xml file in the .vs folder 😅

With empty solution rules the problem happens again:
![image](https://user-images.githubusercontent.com/46932745/196800959-7ead0031-f9ac-4858-8708-e7de14a3c9b9.png)
